import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [{type: "autogenerated", dirName: "docs"}],
  thesisSidebar: [{type: "autogenerated", dirName: "thesis"}],
};
export default sidebars;
